---
$schema: /app-sre/saas-file-2.yml

labels:
  service: alcove

name: alcove
displayName: alcove
description: Deploy Alcove resources

app:
  $ref: /services/alcove/app.yml

pipelinesProvider:
  $ref: /services/app-sre/pipelines/tekton-app-sre-pipelines.appsrep09ue1.yaml
deployResources:
  requests:
    cpu: "1"
    memory: 3000Mi
  limits:
    memory: 3000Mi

clusterAdmin: true
compare: false

managedResourceTypes:
- Deployment
- Service
- ConfigMap
- Secret
- ServiceAccount
- Role
- RoleBinding
- NetworkPolicy

imagePatterns:
- ghcr.io/bmbouter

resourceTemplates:
- name: alcove
  url: https://github.com/bmbouter/alcove
  path: /deploy/openshift/template.yaml
  parameters:
    BRIDGE_REPLICAS: "1"
  targets:
  - namespace:
      $ref: /services/alcove/namespaces/alcove-stage.yml
    ref: main
